"""Export hunt results to investigation graph markdown (Cypher + Mermaid)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from forensics.hunt import QUERIES, run_hunt
from forensics.neo4j_client import Neo4jClient


def _mermaid_for_rows(hunt: str, rows: list[dict[str, Any]]) -> str:
    if not rows:
        return "```mermaid\nflowchart TB\n  empty[No rows returned]\n```\n"

    if hunt in ("photos_outside_home", "photos_during_vacation"):
        lines = ["```mermaid", "flowchart LR"]
        for r in rows[:10]:
            path = str(r.get("path") or "?")[:30]
            lat = r.get("lat") or r.get("latitude")
            lon = r.get("lon") or r.get("longitude")
            lines.append(f'  N["{path}"]')
            if lat is not None and lon is not None:
                lines.append(f'  G["{lat},{lon}"]')
                lines.append("  N --> G")
        lines.append("```")
        return "\n".join(lines) + "\n"

    if hunt in ("cloud_sync_connections", "external_connections"):
        lines = ["```mermaid", "flowchart LR"]
        seen: set[str] = set()
        for r in rows[:12]:
            proc = str(r.get("process") or r.get("name") or "?")[:20]
            ip = str(r.get("ip") or r.get("address") or "?")[:18]
            key = f"{proc}_{ip}"
            if key in seen:
                continue
            seen.add(key)
            pid = r.get("pid", "")
            p_id = f"P_{len(seen)}"
            i_id = f"I_{len(seen)}"
            lines.append(f'  {p_id}["{proc} {pid}"]')
            lines.append(f'  {i_id}["{ip}"]')
            lines.append(f"  {p_id} --> {i_id}")
        lines.append("```")
        return "\n".join(lines) + "\n"

    if "parent" in (rows[0] if rows else {}):
        lines = ["```mermaid", "flowchart TB"]
        for r in rows[:8]:
            par = str(r.get("parent") or "?")
            ch = str(r.get("child") or "?")
            lines.append(f'  P["{par}"] --> C["{ch} PID {r.get("child_pid", "")}"]')
        lines.append("```")
        return "\n".join(lines) + "\n"

    lines = ["| Key | Value |", "|-----|-------|"]
    for r in rows[:15]:
        cells = " | ".join(str(v)[:40] for v in r.values())
        lines.append(f"| {cells} |")
    return "\n".join(lines) + "\n"


def write_graph_doc(
    hunt: str,
    out_path: Path,
    *,
    step_link: str = "",
    hypothesis: str = "",
    extra_cypher: str | None = None,
    case=None,
    client: Neo4jClient | None = None,
) -> Path:
    """Run hunt, write markdown with Cypher block and Mermaid diagram."""
    result = run_hunt(hunt, client=client, case=case)
    rows: list[dict[str, Any]] = result.get("rows") or []
    cypher = extra_cypher or QUERIES.get(hunt, "").strip()

    parts = [
        f"# Graph view: {hunt}",
        "",
    ]
    if step_link:
        parts.append(f"**Step:** {step_link}")
    if hypothesis:
        parts.append(f"**Hypothesis:** {hypothesis}")
    parts.append(f"**Hunt:** `{hunt}`")
    parts.append("")
    parts.append("## Cypher")
    parts.append("")
    parts.append(f"```cypher\n{cypher}\n```")
    parts.append("")
    parts.append(f"## Result snapshot ({len(rows)} rows)")
    parts.append("")
    parts.append(_mermaid_for_rows(hunt, rows))
    parts.append("")
    parts.append("*Generated by `forensics-ingest graph export`*")
    parts.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(parts))
    return out_path
